apiVersion: v1
kind: Secret
metadata:
  name: infrarecord-secrets
  namespace: infrarecord
type: Opaque
stringData:
  db-user: "infrarecord"
  db-password: "infrarecord"
  jwt-secret: "InfraRecordSecureKey2026ChangeInProduction"
